project/cart/urls.py
from django.urls import path
from . import views
# from cart.api.serializers import CartItemSerializer
# from cart.cart_api.views import CartItemListCreateView
# from cart.api.views import add_cart, get_cart
# from .models import CartItem
# from cart.cart_api.views import CartItemListCreateView
# from .views import CartItemListCreateView
# from .serializers import CartItemSerializer
app_name ='cart'
urlpatterns = [
    # path('create_product/', views.create_product, name='create_product'),
    # path('list_products/',views.list_products,name='list_products'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('cart_detail/',views.cart_detail,name='cart_detail'),
    path('inc_quantity/<int:product_id>/',views.inc_quantity,name='inc_quantity'),
    path('dec_quantity/<int:product_id>/',views.dec_quantity,name='dec_quantity'),
    # path('Add/',CartItemListCreateView.as_view(),name='add_item'),
    # path('add/',add_cart,name='add_item'),
    # path('get/',get_cart,name='get_item'),
]

project/project/urls.py
# from django.contrib import admin
# from django.urls import path, include
from django.contrib import admin
from django.urls import path , include,re_path
from django.conf import settings
from django.conf.urls.static import static

from fundproject.views import home 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', home,name='home'),
    path('project/', include('fundproject.urls')),
    path('fundapi/', include('fundapi.urls')),
    re_path('^', include('django.contrib.auth.urls')),
    path('cart/',include('cart.urls')),
    path('cart_api/',include('cart_api.urls')),
    path('product/',include('product.urls')),
    path('product_api/',include('product_api.urls'))


]
# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/cart/models.py
from django.db import models

from users.models import Users
from product.models import Product

# class Product(models.Model):
#     id=models.AutoField(primary_key=True)
#     name = models.CharField(max_length=100)
#     price = models.DecimalField(max_digits=10, decimal_places=2)


# class Product(models.Model):
#     name = models.CharField(max_length=255)
#     description = models.TextField()
#     price = models.DecimalField(max_digits=10, decimal_places=2)
#     # stock = models.IntegerField()
#     image = models.ImageField(upload_to='product_images/', null=True, blank=True)
#
#     def __str__(self):
#         return self.name



class Cart(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)




class CartItem(models.Model):
    cart_id = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

project/cart/views.py
from users.models import Users
from django.db.models import Q, Max, Min
from django.shortcuts import get_object_or_404
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from .models import Cart,CartItem
from product.models import Product
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_protect

# Create your views here.
# @csrf_protect
# def create_product(request):
#     context={}
#     # product=Product.objects.all()
#     if request.method == 'POST':
#         name=request.POST['name']
#         price= request.POST['price']
#         # description=request.POST['description']
#         # image=request.POST['image']
# 
#         product=Product(name=name,price=price)
#         # product.session.create()
#         product.save()
#         context['prod']=product
#         return render(request,'cart/details.html',context)
#     return render(request,'cart/create_product.html',context)
# 
# def list_products(request):
#     context = {}
#     product = Product.objects.all()
#     context['prod'] = product
#     return render(request, 'cart/listing_product.html', context)

@login_required(login_url='/login')
def add_to_cart(request,product_id):
    if 'cart' not in request.session:
        request.session['cart']={}
    cart=request.session['cart']

    product_id_str = str(product_id)
    if str(product_id_str) in cart:
        cart[product_id_str]['quantity']+=1
    else:
        cart[product_id_str]={'quantity':1}

    request.session['cart'] =cart

    product = Product.objects.get(id=product_id)
    cart_obj, created = Cart.objects.get_or_create(user=request.user, is_paid=False)
    cart_item=CartItem.objects.filter(product_id=product_id,cart_id=cart_obj ).first()
    if cart_item:
        cart_item.quantity+=1
        cart_item.save()
        print('added')
    else:

        quantity = cart[product_id_str]['quantity']
        CartItem.objects.create(product_id=product,quantity=quantity,cart_id=cart_obj)
        print('created')
    return redirect('cart:cart_detail')


@login_required
def cart_detail(request):
    # session_cart = request.session.get('cart', {})
    cart_items = []
    total_price = 0
    cart_obj = Cart.objects.filter(user=request.user).first()
    if cart_obj:
        for cart_item in CartItem.objects.filter(cart_id=cart_obj):
            cart_items.append({
                'product_id': cart_item.product_id.id,
                'product_name': cart_item.product_id.name,
                'quantity': cart_item.quantity,
                'price_total': cart_item.product_id.price * cart_item.quantity,
            })
            total_price += cart_item.product_id.price * cart_item.quantity

    context = {
        'cart_items': cart_items,
        'total_price': total_price,
    }
    return render(request, 'cart/cart_detail.html', context)


@login_required(login_url='/login')
def inc_quantity(request,product_id):
    product=Product.objects.get(id=product_id)
    cart_obj = Cart.objects.get(user=request.user, is_paid=False)
    cart_item=CartItem.objects.filter(product_id=product,cart_id=cart_obj).get()
    if cart_item:
        cart_item.quantity+=1
        cart_item.save()
    return redirect('cart:cart_detail')


@login_required(login_url='/login')
def dec_quantity(request,product_id):
    product=Product.objects.get(id=product_id)
    cart_obj = Cart.objects.get(user=request.user, is_paid=False)
    cart_item=CartItem.objects.filter(product_id=product,cart_id=cart_obj).get()
    if cart_item:
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    return redirect('cart:cart_detail')

project/templates/cart/cart_detail.html
<!-- templates/cart/cart_detail.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Cart</title>

</head>
<body>

    <div class="container">
        <h1>Your Cart</h1>

        {% if cart_items %}
            <table border="3">
                <thead>
                    <tr>
                        <th>Product ID</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>inc</th>
                        <th>dec</th>

                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                        <tr>
                            <td>{{ item.product_id }}</td>
                            <td>{{ item.quantity }}</td>
                            <td>${{ item.price_total|floatformat:2 }}</td>
                            <td>
                                 <button onclick="location.href='{% url 'cart:inc_quantity' item.product_id %}'">+</button>
                            </td>
                            <td>
                                <button onclick="location.href='{% url 'cart:dec_quantity' item.product_id %}'">-</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <h3>Total: ${{ total_price|floatformat:2 }}</h3>
        {% else %}
            <p>Your cart is empty.</p>
        {% endif %}

    </div>
</body>
</html>ml>

project/templates/cart/create_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>create</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <label for="name">Name</label>
        <input id="name" name="name" type="text" required>

        <label for="price">Price</label>
        <input id="price" name="price" type="number" step="0.01" required>

        <button type="submit">Create Product</button>
    </form>


</body>
</html>

project/templates/cart/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>details</title>
</head>
<body>
<h1>Details product</h1>
</body>
</html>

project/templates/cart/listing_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>list</title>
</head>
<body>

{% for p in prod %}
    <div>
        <h4>name : {{ p.name }}</h4>
        <h4>price : {{ p.price }}</h4>
        <div>
            <button>
                details
            </button>
             <button onclick="window.location.href='{% url 'cart:add_to_cart' p.id %}'">
               Add_to_cart
            </button>
        </div>
    </div>

{% endfor %}

</body>
</html>